// auto-generated by sequelize-cli

const fs = require('fs')
const path = require('path')
const Sequelize = require('sequelize')
const basename = path.basename(__filename)
const { database: config } = require('../../config')

const sequelize = new Sequelize(config.url, config)

const db = fs
  .readdirSync(__dirname)
  .filter(file => (file.indexOf('.') !== 0) && (file !== basename) && (file.slice(-3) === '.js'))
  .reduce((models, file) => {
    const model = sequelize.import(path.join(__dirname, file))
    return ({
      ...models,
      [model.name]: model,
    })
  }, {})

Object.values(db).forEach(model => {
  if (model.associate) {
    model.associate(db)
  }
})

db.sequelize = sequelize
db.Sequelize = Sequelize

db.authenticate = sequelize.authenticate.bind(sequelize)

module.exports = db
